import { useState } from 'react'
import { Clock3, CirclePlus, MessageCircle, Star } from 'lucide-react'
import { gigs } from '../data/gigs'
import { Field, PageShell, Stat } from '../components/PageShell'
import { GigCard } from '../components/GigCard'
import type { Category, Gig, NewGig } from '../types'

type GigPageProps = { gig: Gig; onBack: () => void; onProfile: () => void; onRequest: () => void }

export function GigPage({ gig, onBack, onProfile, onRequest }: GigPageProps) {
  return <PageShell eyebrow="02 · Gig detail" title={gig.title} description="A closer look at the offer, provider reputation, and what happens next."><button onClick={onBack} className="mb-6 flex items-center gap-2 text-xs font-semibold text-coral">← Back to the board</button><div className="grid gap-7 md:grid-cols-[1.2fr_.8fr]"><article className="paper-grain rounded bg-paper p-7 text-board shadow-note" style={{ transform: 'rotate(-.6deg)' }}><span className={`rounded px-2 py-1 font-mono text-[10px] font-semibold uppercase ${gig.tag}`}>{gig.category}</span><h2 className="mt-5 font-display text-2xl font-bold">{gig.title}</h2><p className="mt-2 text-xs text-[#6b6980]">Posted 3 days ago · {gig.reviews} orders completed</p><p className="mt-6 text-sm leading-6 text-[#4d4b5c]">{gig.description}</p><p className="mt-7 font-mono text-2xl font-medium">{gig.price}</p><p className="mt-2 flex items-center gap-1 text-xs text-[#6b6980]"><Clock3 size={13} /> Delivery: {gig.delivery}</p></article><div className="space-y-4"><div className="rounded-xl border border-white/10 bg-board-alt p-5"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-lav font-mono text-xs font-bold text-board">{gig.person.split(' ').map((name) => name[0]).join('')}</div><div><p className="text-sm font-semibold">{gig.person}</p><p className="mt-1 font-mono text-[11px] text-white/45"><Star size={11} className="mr-1 inline fill-sun text-sun" />{gig.rating} · {gig.reviews} gigs completed</p></div></div><button onClick={onProfile} className="mt-5 w-full rounded-lg border border-white/20 px-4 py-2 text-xs font-semibold hover:border-white/50">View profile</button></div><div className="rounded-xl border border-white/10 bg-board-alt p-5"><p className="mb-3 text-xs text-white/50">Ready to request this gig?</p><button onClick={onRequest} className="w-full rounded-lg bg-coral px-4 py-3 text-sm font-semibold text-board hover:bg-[#e1493a]">Request this gig · {gig.price}</button></div></div></div></PageShell>
}

export function ProfilePage({ onGig }: { onGig: (gig: Gig) => void }) {
  return <PageShell eyebrow="03 · Community" title="Chidi Anyanwu" description="CS department · Building useful things for people around the board."><div className="mb-7 flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-lav font-mono text-lg font-bold text-board">CA</div><div><p className="font-mono text-xs text-white/50">4.8 rating · 23 gigs completed</p><p className="mt-1 text-sm text-white/55">Usually responds in under 2 hours</p></div></div><div className="grid gap-4 sm:grid-cols-3"><Stat label="Rating" value="4.8" /><Stat label="Completed" value="23" /><Stat label="Response" value="&lt; 2 hrs" /></div><p className="mb-4 mt-10 font-mono text-[11px] uppercase tracking-[.18em] text-sun">Active gigs</p><div className="grid gap-7 sm:grid-cols-2">{gigs.filter((gig) => gig.person === 'Chidi Anyanwu').map((gig, index) => <GigCard key={gig.id} gig={gig} index={index} onOpen={() => onGig(gig)} />)}</div></PageShell>
}

export function CreatePage({ newGig, setNewGig, onSubmit }: { newGig: NewGig; setNewGig: React.Dispatch<React.SetStateAction<NewGig>>; onSubmit: () => void }) {
  const update = (field: keyof NewGig, value: string) => setNewGig((current) => ({ ...current, [field]: value }))
  return <PageShell eyebrow="04 · Create a gig" title="Pin a new skill" description="Give the community enough detail to know what you can do and when you can deliver it."><div className="grid gap-8 md:grid-cols-[1fr_280px]"><form onSubmit={(event) => { event.preventDefault(); onSubmit() }} className="rounded-2xl border border-white/10 bg-board-alt p-6"><Field label="Title"><input required value={newGig.title} onChange={(event) => update('title', event.target.value)} placeholder="e.g. I'll fix your laptop screen" /></Field><Field label="Category"><select value={newGig.category} onChange={(event) => update('category', event.target.value as Category)}>{['Design', 'Dev', 'Repairs', 'Writing', 'Tutoring'].map((category) => <option key={category}>{category}</option>)}</select></Field><Field label="Description"><textarea required rows={5} value={newGig.description} onChange={(event) => update('description', event.target.value)} placeholder="What's included, turnaround time, revisions..." /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Price (₦)"><input required value={newGig.price} onChange={(event) => update('price', event.target.value)} placeholder="6500" /></Field><Field label="Delivery time"><input required value={newGig.delivery} onChange={(event) => update('delivery', event.target.value)} placeholder="3 days" /></Field></div><button className="mt-2 flex items-center gap-2 rounded-lg bg-coral px-4 py-3 text-sm font-semibold text-board"><CirclePlus size={16} /> Pin this gig</button></form><div className="flex items-center justify-center"><article className="note-tilt paper-grain relative w-full rounded bg-paper p-5 text-board shadow-note" style={{ '--rotation': '-2deg' } as React.CSSProperties}><span className="absolute left-1/2 top-[-7px] h-3.5 w-3.5 -translate-x-1/2 rounded-full bg-mint" /><span className="rounded bg-[#e9fbf5] px-2 py-1 font-mono text-[10px] font-semibold uppercase text-[#22a87e]">{newGig.category}</span><h2 className="mt-5 min-h-14 font-display text-xl font-bold">{newGig.title || 'Your new gig'}</h2><p className="mt-3 min-h-20 text-sm leading-6 text-[#4d4b5c]">{newGig.description || 'Add a clear description so people know exactly what you can help with.'}</p><p className="mt-5 font-mono">{newGig.price ? `₦${newGig.price}` : 'Your price'}</p></article></div></div></PageShell>
}

export function OrdersPage({ tab, setTab, onOpen }: { tab: 'requester' | 'provider'; setTab: (tab: 'requester' | 'provider') => void; onOpen: () => void }) {
  return <PageShell eyebrow="05 · My orders" title="Keep the work moving" description="Track requests you made and gigs you are delivering from one board."><div className="mb-7 flex gap-2"><button onClick={() => setTab('requester')} className={`rounded-full border px-4 py-2 font-mono text-[11px] ${tab === 'requester' ? 'border-coral bg-coral text-board' : 'border-white/15 text-white/60'}`}>As requester (2)</button><button onClick={() => setTab('provider')} className={`rounded-full border px-4 py-2 font-mono text-[11px] ${tab === 'provider' ? 'border-coral bg-coral text-board' : 'border-white/15 text-white/60'}`}>As provider (3)</button></div><div className="grid gap-7 sm:grid-cols-2">{(tab === 'requester' ? gigs.slice(0, 2) : gigs.slice(2, 5)).map((gig) => <button key={gig.id} onClick={onOpen} className="text-left"><article className="note-tilt paper-grain relative rounded bg-paper p-5 text-board shadow-note" style={{ '--rotation': gig.rotation } as React.CSSProperties}><span className={`absolute left-1/2 top-[-7px] h-3.5 w-3.5 -translate-x-1/2 rounded-full ${gig.pin}`} /><span className={`rounded px-2 py-1 font-mono text-[10px] font-semibold uppercase ${gig.tag}`}>{gig.category}</span><h2 className="mt-5 font-display text-xl font-bold">{gig.title}</h2><p className="mt-2 text-xs text-[#6b6980]">{tab === 'requester' ? `${gig.person} · In progress` : 'Requester · In progress'}</p><p className="mt-6 font-mono">{gig.price}</p></article></button>)}</div></PageShell>
}

export function OrderPage({ onBack, onSend }: { onBack: () => void; onSend: () => void }) {
  const [message, setMessage] = useState('')
  return <PageShell eyebrow="06 · Order #GB-1042" title="I'll design your logo" description="With Chidi Anyanwu · ₦4,000"><button onClick={onBack} className="mb-6 text-xs font-semibold text-coral">← Back to orders</button><div className="mb-8 grid grid-cols-2 gap-2 sm:grid-cols-5">{['Requested', 'Accepted', 'In progress', 'Delivered', 'Completed'].map((step, index) => <div key={step} className="border-t-2 pt-3" style={{ borderColor: index < 3 ? '#3ed9a7' : 'rgba(251,248,242,.2)' }}><p className="text-xs font-semibold">{step}</p><p className="mt-1 font-mono text-[10px] text-white/40">{index < 2 ? 'Aug 30' : index === 2 ? 'Now' : '—'}</p></div>)}</div><div className="rounded-xl border border-white/10 bg-board-alt p-5"><div className="mb-4 max-w-md rounded-lg rounded-tl-none bg-board p-3 text-sm">Sent you 2 initial concepts. Let me know which direction you like.</div><div className="mb-5 ml-auto max-w-md rounded-lg rounded-tr-none bg-coral p-3 text-sm text-board">Love the second one, can we try it in green instead?</div><form onSubmit={(event) => { event.preventDefault(); if (message.trim()) { onSend(); setMessage('') } }} className="flex gap-2"><input value={message} onChange={(event) => setMessage(event.target.value)} className="w-full rounded-lg border border-white/10 bg-board px-3 py-3 text-sm text-paper outline-none" placeholder="Type a message..." /><button className="rounded-lg bg-coral px-4 py-2 text-sm font-semibold text-board">Send</button></form></div></PageShell>
}
