import { useEffect, useMemo, useState } from 'react'
import { Bell, BriefcaseBusiness, Check, ChevronRight, CirclePlus, Clock3, Compass, Menu, MessageCircle, Search, SlidersHorizontal, Star, X } from 'lucide-react'

type Category = 'Design' | 'Repairs' | 'Writing' | 'Dev' | 'Tutoring'
type Gig = { id: number; category: Category; title: string; person: string; department: string; price: string; rating: string; reviews: number; delivery: string; description: string; pin: string; tag: string; rotation: string }

const gigs: Gig[] = [
  { id: 1, category: 'Design', title: "I'll design your logo", person: 'Chidi Anyanwu', department: 'CS dept.', price: '₦4,000', rating: '4.8', reviews: 23, delivery: '3 days', description: 'Clean, simple logo design with 2 concepts and up to 2 rounds of revisions. Delivered as PNG and SVG.', pin: 'bg-coral', tag: 'bg-[#fff0ed] text-[#e1493a]', rotation: '-1.2deg' },
  { id: 2, category: 'Repairs', title: 'Laptop screen & battery fix', person: 'Israel Olasupo', department: 'CS dept.', price: '₦6,500', rating: '5.0', reviews: 18, delivery: '1 day', description: 'Fast, careful hardware fixes for common laptop screen and battery issues. Parts are quoted before work starts.', pin: 'bg-mint', tag: 'bg-[#e9fbf5] text-[#22a87e]', rotation: '1deg' },
  { id: 3, category: 'Writing', title: 'Essay editing & proofreading', person: 'Ngozi Eze', department: 'English dept.', price: '₦2,000', rating: '4.6', reviews: 31, delivery: '2 days', description: 'Clearer structure, stronger grammar, and a final proofread for essays, applications, and personal projects.', pin: 'bg-sun', tag: 'bg-[#fff7df] text-[#c08311]', rotation: '-.6deg' },
  { id: 4, category: 'Dev', title: 'Build you a simple landing page', person: 'Tunde Balogun', department: 'CS dept.', price: '₦12,000', rating: '4.9', reviews: 12, delivery: '5 days', description: 'A polished, responsive landing page for your project or small business, built with clean modern code.', pin: 'bg-lav', tag: 'bg-[#f0eeff] text-[#7160d5]', rotation: '.8deg' },
  { id: 5, category: 'Tutoring', title: '1-on-1 calculus tutoring', person: 'Grace Emmanuel', department: 'Maths dept.', price: '₦1,500/hr', rating: '4.8', reviews: 26, delivery: 'Flexible', description: 'Patient, one-on-one help with calculus topics, past questions, and building confidence before exams.', pin: 'bg-coral', tag: 'bg-[#fff0ed] text-[#e1493a]', rotation: '-1deg' },
  { id: 6, category: 'Dev', title: 'Debug your school project code', person: 'Israel Olasupo', department: 'CS dept.', price: '₦3,000', rating: '5.0', reviews: 18, delivery: '2 days', description: 'Find the bug, explain what happened, and get your project back on track without the mystery.', pin: 'bg-mint', tag: 'bg-[#e9fbf5] text-[#22a87e]', rotation: '.4deg' },
]
const categories: Array<'All' | Category> = ['All', 'Design', 'Dev', 'Repairs', 'Writing', 'Tutoring']

function App() {
  type View = 'browse' | 'gig' | 'profile' | 'create' | 'orders' | 'order' | 'auth'
  const [activeCategory, setActiveCategory] = useState<'All' | Category>('All')
  const [query, setQuery] = useState('')
  const [selectedGig, setSelectedGig] = useState<Gig | null>(null)
  const [mobileNav, setMobileNav] = useState(false)
  const [view, setView] = useState<View>('browse')
  const [notice, setNotice] = useState('')
  const [orderTab, setOrderTab] = useState<'requester' | 'provider'>('requester')
  const [newGig, setNewGig] = useState({ title: '', category: 'Design' as Category, description: '', price: '', delivery: '' })
  const filteredGigs = useMemo(() => gigs.filter((gig) => (activeCategory === 'All' || gig.category === activeCategory) && `${gig.title} ${gig.person} ${gig.category}`.toLowerCase().includes(query.toLowerCase())), [activeCategory, query])

  const navigate = (nextView: View, gig: Gig | null = null) => {
    setView(nextView)
    setSelectedGig(gig)
    setMobileNav(false)
    window.history.replaceState(null, '', nextView === 'browse' ? '#browse' : `#${nextView}`)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  useEffect(() => {
    const syncView = () => {
      const hash = window.location.hash.slice(1) as View
      if (['browse', 'gig', 'profile', 'create', 'orders', 'order', 'auth'].includes(hash)) setView(hash)
    }
    syncView()
    window.addEventListener('popstate', syncView)
    return () => window.removeEventListener('popstate', syncView)
  }, [])

  const showNotice = (message: string) => {
    setNotice(message)
    window.setTimeout(() => setNotice(''), 3000)
  }

  return (
    <div className="board-texture min-h-screen bg-board text-paper">
      <header className="sticky top-0 z-30 border-b border-white/10 bg-board/95 backdrop-blur-md">
        <div className="mx-auto flex h-[72px] max-w-[1440px] items-center justify-between px-5 lg:px-8">
          <div className="flex items-center gap-3"><button className="rounded-lg p-2 text-white/70 hover:bg-white/10 lg:hidden" onClick={() => setMobileNav(true)} aria-label="Open menu"><Menu size={21} /></button><div className="flex items-center gap-2.5"><span className="h-3.5 w-3.5 rounded-full bg-coral shadow-[0_2px_5px_rgba(0,0,0,.5)]" /><span className="font-display text-lg font-bold tracking-tight">GigBoard</span></div></div>
          <div className="hidden items-center gap-8 text-sm text-white/55 lg:flex"><button onClick={() => navigate('browse')} className={view === 'browse' ? 'font-semibold text-paper' : 'hover:text-paper'}>Browse gigs</button><button onClick={() => document.getElementById('how')?.scrollIntoView({ behavior: 'smooth' })} className="hover:text-paper">How it works</button><button onClick={() => navigate('profile')} className="hover:text-paper">Community</button></div>
          <div className="flex items-center gap-2"><button onClick={() => navigate('orders')} className="hidden items-center gap-2 rounded-lg border border-white/20 px-3 py-2 text-xs font-semibold text-paper transition hover:border-white/50 sm:flex"><BriefcaseBusiness size={15} /> My orders</button><button onClick={() => showNotice('You are all caught up.')} className="rounded-lg border border-white/15 p-2 text-white/70 hover:bg-white/10" aria-label="Notifications"><Bell size={17} /></button><button onClick={() => navigate('create')} className="hidden items-center gap-2 rounded-lg bg-coral px-4 py-2.5 text-sm font-semibold text-board transition hover:bg-[#e1493a] sm:flex"><CirclePlus size={16} /> Post a gig</button><button onClick={() => navigate('profile')} className="ml-1 flex h-9 w-9 items-center justify-center rounded-lg bg-lav font-mono text-xs font-bold text-board" aria-label="Open profile">IO</button></div>
        </div>
      </header>

      {mobileNav && <div className="fixed inset-0 z-50 bg-board/80 lg:hidden" onClick={() => setMobileNav(false)}><aside className="h-full w-72 border-r border-white/10 bg-board-alt p-5" onClick={(event) => event.stopPropagation()}><div className="mb-10 flex items-center justify-between"><span className="font-display text-xl font-bold">GigBoard</span><button onClick={() => setMobileNav(false)} aria-label="Close menu"><X size={20} /></button></div><nav className="grid gap-2 text-sm"><button onClick={() => navigate('browse')} className="rounded-lg bg-white/10 px-4 py-3 text-left font-semibold">Browse gigs</button><button onClick={() => navigate('orders')} className="rounded-lg px-4 py-3 text-left text-white/60">My orders</button><button onClick={() => navigate('create')} className="rounded-lg px-4 py-3 text-left text-white/60">Post a gig</button><button onClick={() => navigate('profile')} className="rounded-lg px-4 py-3 text-left text-white/60">Community</button></nav></aside></div>}

      {notice && <div className="fixed bottom-5 left-1/2 z-50 flex -translate-x-1/2 items-center gap-2 rounded-lg bg-mint px-4 py-3 text-sm font-semibold text-board shadow-2xl"><Check size={16} /> {notice}</div>}
      {view === 'gig' && selectedGig && <GigPage gig={selectedGig} onBack={() => navigate('browse')} onProfile={() => navigate('profile')} onRequest={() => { showNotice('Request sent. Check My orders for updates.'); navigate('orders') }} />}
      {view === 'profile' && <ProfilePage onGig={(gig) => navigate('gig', gig)} />}
      {view === 'create' && <CreatePage newGig={newGig} setNewGig={setNewGig} onSubmit={() => { showNotice('Your gig is pinned to the board.'); navigate('browse') }} />}
      {view === 'orders' && <OrdersPage tab={orderTab} setTab={setOrderTab} onOpen={() => navigate('order')} />}
      {view === 'order' && <OrderPage onBack={() => navigate('orders')} onSend={() => showNotice('Message sent.')} />}
      {view === 'auth' && <AuthPage onSubmit={() => { showNotice('Welcome to the board.'); navigate('browse') }} />}
      {view === 'browse' && <main id="browse" className="mx-auto max-w-[1440px] px-5 pb-24 pt-10 lg:px-8 lg:pt-14">
        <div className="mb-10 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="max-w-xl"><p className="mb-3 font-mono text-[11px] uppercase tracking-[.18em] text-sun">01 · The board</p><h1 className="font-display text-4xl font-bold leading-[1.05] tracking-tight sm:text-5xl">Find someone who<br /><span className="text-coral">gets it done.</span></h1><p className="mt-4 max-w-md text-sm leading-6 text-white/55">Useful things, made by people around you. Browse the board or pin your own skill for the community to find.</p></div><div className="flex items-center gap-2 text-xs text-white/45"><span className="h-2 w-2 rounded-full bg-mint" /> 128 active gigs this week <ChevronRight size={14} /></div></div>

        <section className="rounded-2xl border border-white/10 bg-board-alt/80 p-4 shadow-note sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><label className="flex min-h-12 flex-1 items-center gap-3 rounded-xl border border-white/10 bg-board px-4 text-white/45 focus-within:border-coral/60"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent text-sm text-paper outline-none placeholder:text-white/35" placeholder="Search gigs, skills, or people..." /></label><button className="flex items-center justify-center gap-2 rounded-xl border border-white/15 px-4 py-3 text-sm text-white/65 hover:border-white/40"><SlidersHorizontal size={16} /> Filters</button></div><div className="mt-4 flex gap-2 overflow-x-auto pb-1">{categories.map((category) => <button key={category} onClick={() => setActiveCategory(category)} className={`whitespace-nowrap rounded-full border px-4 py-2 font-mono text-[11px] transition ${activeCategory === category ? 'border-coral bg-coral font-medium text-board' : 'border-white/15 text-white/60 hover:border-white/40'}`}>{category}</button>)}</div></section>

        <div className="mb-4 mt-10 flex items-center justify-between"><div><p className="font-display text-xl font-bold">Pinned this week</p><p className="mt-1 text-xs text-white/40">{filteredGigs.length} opportunities on the board</p></div><button className="hidden items-center gap-2 text-xs font-semibold text-coral sm:flex">Sort: Recommended <ChevronRight size={14} /></button></div>
        {filteredGigs.length ? <div className="grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-2 xl:grid-cols-3">{filteredGigs.map((gig, index) => <GigCard key={gig.id} gig={gig} index={index} onOpen={() => navigate('gig', gig)} />)}</div> : <div className="rounded-xl border border-dashed border-white/20 py-16 text-center text-sm text-white/50">No gigs match that search yet.</div>}

        <section id="how" className="mt-28 grid gap-6 border-t border-white/10 pt-10 md:grid-cols-3"><Step icon={<Compass size={18} />} number="01" title="Find your person" text="Search the board for a useful skill, a fair price, and a good fit." /><Step icon={<MessageCircle size={18} />} number="02" title="Start a conversation" text="Request a gig and work out the details directly with the provider." /><Step icon={<Star size={18} />} number="03" title="Build the board" text="When the work is done, leave a rating and help the next person choose." /></section>
      </main>}
    </div>
  )
}

function PageShell({ eyebrow, title, description, children }: { eyebrow: string; title: string; description: string; children: React.ReactNode }) {
  return <main className="mx-auto max-w-[1100px] px-5 pb-24 pt-10 lg:px-8 lg:pt-14"><div className="mb-8 max-w-2xl"><p className="mb-3 font-mono text-[11px] uppercase tracking-[.18em] text-sun">{eyebrow}</p><h1 className="font-display text-4xl font-bold leading-tight sm:text-5xl">{title}</h1><p className="mt-4 text-sm leading-6 text-white/55">{description}</p></div>{children}</main>
}

function GigPage({ gig, onBack, onProfile, onRequest }: { gig: Gig; onBack: () => void; onProfile: () => void; onRequest: () => void }) {
  return <PageShell eyebrow="02 · Gig detail" title={gig.title} description="A closer look at the offer, provider reputation, and what happens next."><button onClick={onBack} className="mb-6 flex items-center gap-2 text-xs font-semibold text-coral">← Back to the board</button><div className="grid gap-7 md:grid-cols-[1.2fr_.8fr]"><article className="paper-grain rounded bg-paper p-7 text-board shadow-note" style={{ transform: 'rotate(-.6deg)' }}><span className={`rounded px-2 py-1 font-mono text-[10px] font-semibold uppercase ${gig.tag}`}>{gig.category}</span><h2 className="mt-5 font-display text-2xl font-bold">{gig.title}</h2><p className="mt-2 text-xs text-[#6b6980]">Posted 3 days ago · {gig.reviews} orders completed</p><p className="mt-6 text-sm leading-6 text-[#4d4b5c]">{gig.description}</p><p className="mt-7 font-mono text-2xl font-medium">{gig.price}</p><p className="mt-2 flex items-center gap-1 text-xs text-[#6b6980]"><Clock3 size={13} /> Delivery: {gig.delivery}</p></article><div className="space-y-4"><div className="rounded-xl border border-white/10 bg-board-alt p-5"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-lav font-mono text-xs font-bold text-board">{gig.person.split(' ').map((name) => name[0]).join('')}</div><div><p className="text-sm font-semibold">{gig.person}</p><p className="mt-1 font-mono text-[11px] text-white/45"><Star size={11} className="mr-1 inline fill-sun text-sun" />{gig.rating} · {gig.reviews} gigs completed</p></div></div><button onClick={onProfile} className="mt-5 w-full rounded-lg border border-white/20 px-4 py-2 text-xs font-semibold hover:border-white/50">View profile</button></div><div className="rounded-xl border border-white/10 bg-board-alt p-5"><p className="mb-3 text-xs text-white/50">Ready to request this gig?</p><button onClick={onRequest} className="w-full rounded-lg bg-coral px-4 py-3 text-sm font-semibold text-board hover:bg-[#e1493a]">Request this gig · {gig.price}</button></div></div></div></PageShell>
}

function ProfilePage({ onGig }: { onGig: (gig: Gig) => void }) {
  return <PageShell eyebrow="03 · Community" title="Chidi Anyanwu" description="CS department · Building useful things for people around the board."><div className="mb-7 flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-lav font-mono text-lg font-bold text-board">CA</div><div><p className="font-mono text-xs text-white/50">4.8 rating · 23 gigs completed</p><p className="mt-1 text-sm text-white/55">Usually responds in under 2 hours</p></div></div><div className="grid gap-4 sm:grid-cols-3"><Stat label="Rating" value="4.8" /><Stat label="Completed" value="23" /><Stat label="Response" value="&lt; 2 hrs" /></div><p className="mb-4 mt-10 font-mono text-[11px] uppercase tracking-[.18em] text-sun">Active gigs</p><div className="grid gap-7 sm:grid-cols-2">{gigs.filter((gig) => gig.person === 'Chidi Anyanwu').map((gig, index) => <GigCard key={gig.id} gig={gig} index={index} onOpen={() => onGig(gig)} />)}</div></PageShell>
}

function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-board-alt p-5"><p className="font-mono text-[10px] uppercase tracking-wide text-white/45">{label}</p><p className="mt-2 font-display text-2xl font-bold" dangerouslySetInnerHTML={{ __html: value }} /></div> }

function CreatePage({ newGig, setNewGig, onSubmit }: { newGig: { title: string; category: Category; description: string; price: string; delivery: string }; setNewGig: React.Dispatch<React.SetStateAction<{ title: string; category: Category; description: string; price: string; delivery: string }>>; onSubmit: () => void }) {
  const update = (field: keyof typeof newGig, value: string) => setNewGig((current) => ({ ...current, [field]: value }))
  return <PageShell eyebrow="04 · Create a gig" title="Pin a new skill" description="Give the community enough detail to know what you can do and when you can deliver it."><div className="grid gap-8 md:grid-cols-[1fr_280px]"><form onSubmit={(event) => { event.preventDefault(); onSubmit() }} className="rounded-2xl border border-white/10 bg-board-alt p-6"><Field label="Title"><input required value={newGig.title} onChange={(event) => update('title', event.target.value)} placeholder="e.g. I'll fix your laptop screen" /></Field><Field label="Category"><select value={newGig.category} onChange={(event) => update('category', event.target.value)}>{categories.slice(1).map((category) => <option key={category}>{category}</option>)}</select></Field><Field label="Description"><textarea required rows={5} value={newGig.description} onChange={(event) => update('description', event.target.value)} placeholder="What's included, turnaround time, revisions..." /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Price (₦)"><input required value={newGig.price} onChange={(event) => update('price', event.target.value)} placeholder="6500" /></Field><Field label="Delivery time"><input required value={newGig.delivery} onChange={(event) => update('delivery', event.target.value)} placeholder="3 days" /></Field></div><button className="mt-2 flex items-center gap-2 rounded-lg bg-coral px-4 py-3 text-sm font-semibold text-board"><CirclePlus size={16} /> Pin this gig</button></form><div className="flex items-center justify-center"><article className="note-tilt paper-grain relative w-full rounded bg-paper p-5 text-board shadow-note" style={{ '--rotation': '-2deg' } as React.CSSProperties}><span className="absolute left-1/2 top-[-7px] h-3.5 w-3.5 -translate-x-1/2 rounded-full bg-mint" /><span className="rounded bg-[#e9fbf5] px-2 py-1 font-mono text-[10px] font-semibold uppercase text-[#22a87e]">{newGig.category}</span><h2 className="mt-5 min-h-14 font-display text-xl font-bold">{newGig.title || 'Your gig title'}</h2><p className="mt-2 min-h-12 text-xs text-[#6b6980]">by You · CS dept.</p><p className="mt-5 min-h-12 text-sm text-[#4d4b5c]">{newGig.description || 'Your description will appear here.'}</p><p className="mt-5 font-mono text-lg">{newGig.price ? `₦${newGig.price}` : '₦0'}</p></article></div></div></PageShell>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="mb-4 block text-xs font-semibold text-paper"><span className="mb-2 block">{label}</span>{children}</label> }

function OrdersPage({ tab, setTab, onOpen }: { tab: 'requester' | 'provider'; setTab: (tab: 'requester' | 'provider') => void; onOpen: () => void }) {
  return <PageShell eyebrow="05 · My orders" title="Keep the work moving" description="Track requests you made and gigs you are delivering from one board."><div className="mb-7 flex gap-2"><button onClick={() => setTab('requester')} className={`rounded-full border px-4 py-2 font-mono text-[11px] ${tab === 'requester' ? 'border-coral bg-coral text-board' : 'border-white/15 text-white/60'}`}>As requester (2)</button><button onClick={() => setTab('provider')} className={`rounded-full border px-4 py-2 font-mono text-[11px] ${tab === 'provider' ? 'border-coral bg-coral text-board' : 'border-white/15 text-white/60'}`}>As provider (3)</button></div><div className="grid gap-7 sm:grid-cols-2">{(tab === 'requester' ? gigs.slice(0, 2) : gigs.slice(2, 5)).map((gig, index) => <button key={gig.id} onClick={onOpen} className="text-left"><article className="note-tilt paper-grain relative rounded bg-paper p-5 text-board shadow-note" style={{ '--rotation': gig.rotation } as React.CSSProperties}><span className={`absolute left-1/2 top-[-7px] h-3.5 w-3.5 -translate-x-1/2 rounded-full ${gig.pin}`} /><span className={`rounded px-2 py-1 font-mono text-[10px] font-semibold uppercase ${gig.tag}`}>{gig.category}</span><h2 className="mt-5 font-display text-xl font-bold">{gig.title}</h2><p className="mt-2 text-xs text-[#6b6980]">{tab === 'requester' ? `${gig.person} · In progress` : 'Requester · In progress'}</p><p className="mt-6 font-mono">{gig.price}</p></article></button>)}</div></PageShell>
}

function OrderPage({ onBack, onSend }: { onBack: () => void; onSend: () => void }) { const [message, setMessage] = useState(''); return <PageShell eyebrow="06 · Order #GB-1042" title="I'll design your logo" description="With Chidi Anyanwu · ₦4,000"><button onClick={onBack} className="mb-6 text-xs font-semibold text-coral">← Back to orders</button><div className="mb-8 grid grid-cols-2 gap-2 sm:grid-cols-5">{['Requested', 'Accepted', 'In progress', 'Delivered', 'Completed'].map((step, index) => <div key={step} className="border-t-2 pt-3" style={{ borderColor: index < 3 ? '#3ed9a7' : 'rgba(251,248,242,.2)' }}><p className="text-xs font-semibold">{step}</p><p className="mt-1 font-mono text-[10px] text-white/40">{index < 2 ? 'Aug 30' : index === 2 ? 'Now' : '—'}</p></div>)}</div><div className="rounded-xl border border-white/10 bg-board-alt p-5"><div className="mb-4 max-w-md rounded-lg rounded-tl-none bg-board p-3 text-sm">Sent you 2 initial concepts. Let me know which direction you like.</div><div className="mb-5 ml-auto max-w-md rounded-lg rounded-tr-none bg-coral p-3 text-sm text-board">Love the second one, can we try it in green instead?</div><form onSubmit={(event) => { event.preventDefault(); if (message.trim()) { onSend(); setMessage('') } }} className="flex gap-2"><input value={message} onChange={(event) => setMessage(event.target.value)} className="w-full rounded-lg border border-white/10 bg-board px-3 py-3 text-sm text-paper outline-none" placeholder="Type a message..." /><button className="rounded-lg bg-coral px-4 py-2 text-sm font-semibold text-board">Send</button></form></div></PageShell> }

function AuthPage({ onSubmit }: { onSubmit: () => void }) { return <PageShell eyebrow="07 · Welcome" title="Join the board" description="Post gigs, request one, and build a reputation around useful work."><form onSubmit={(event) => { event.preventDefault(); onSubmit() }} className="paper-grain mx-auto max-w-md rounded bg-paper p-7 text-board shadow-note" style={{ transform: 'rotate(-.5deg)' }}><Field label="Name"><input required placeholder="Israel Olasupo" /></Field><Field label="School / community email"><input required type="email" placeholder="you@atiba.edu.ng" /></Field><Field label="Password"><input required type="password" placeholder="Create a password" /></Field><button className="mt-2 w-full rounded-lg bg-coral px-4 py-3 text-sm font-semibold text-board">Create account</button><p className="mt-4 text-center text-xs text-[#6b6980]">Already on the board? <button type="button" className="font-semibold text-[#e1493a]">Log in</button></p></form></PageShell> }

function GigCard({ gig, index, onOpen }: { gig: Gig; index: number; onOpen: () => void }) { return <button onClick={onOpen} className="animate-rise block w-full text-left" style={{ animationDelay: `${index * 60}ms` }}><article className="note-tilt paper-grain relative min-h-[245px] rounded bg-paper p-5 text-board shadow-note" style={{ '--rotation': gig.rotation } as React.CSSProperties}><span className={`absolute left-1/2 top-[-7px] h-3.5 w-3.5 -translate-x-1/2 rounded-full ${gig.pin} shadow-[0_3px_5px_rgba(0,0,0,.45)]`} /><div className="flex items-center justify-between"><span className={`rounded px-2 py-1 font-mono text-[10px] font-semibold uppercase tracking-wide ${gig.tag}`}>{gig.category}</span><span className="flex items-center gap-1 font-mono text-[11px] text-[#6b6980]"><Star size={12} className="fill-sun text-sun-deep" /> {gig.rating} ({gig.reviews})</span></div><h2 className="mt-5 font-display text-xl font-bold leading-tight">{gig.title}</h2><p className="mt-2 text-xs text-[#6b6980]">by {gig.person} · {gig.department}</p><div className="mt-6 flex items-end justify-between"><div><p className="font-mono text-lg font-medium">{gig.price}</p><p className="mt-1 flex items-center gap-1 text-[11px] text-[#6b6980]"><Clock3 size={12} /> Delivery: {gig.delivery}</p></div><span className="flex h-8 w-8 items-center justify-center rounded-full border border-board/15 text-board/50"><ChevronRight size={16} /></span></div></article></button> }

function Step({ icon, number, title, text }: { icon: React.ReactNode; number: string; title: string; text: string }) { return <div className="flex gap-4"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-board-alt text-mint">{icon}</span><div><p className="font-mono text-[10px] text-sun">{number}</p><h3 className="mt-1 font-display text-base font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-white/45">{text}</p></div></div> }

function GigDetail({ gig, onClose }: { gig: Gig; onClose: () => void }) { return <div className="fixed inset-0 z-40 flex items-end justify-center bg-board/75 p-0 backdrop-blur-sm sm:items-center sm:p-6" onClick={onClose}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-t-2xl border border-white/10 bg-board-alt p-6 shadow-2xl sm:rounded-2xl" onClick={(event) => event.stopPropagation()}><div className="mb-8 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[.15em] text-sun">Gig detail</span><button onClick={onClose} className="rounded-lg p-2 text-white/60 hover:bg-white/10" aria-label="Close gig detail"><X size={19} /></button></div><div className="grid gap-7 md:grid-cols-[1.2fr_.8fr]"><div className="paper-grain rounded bg-paper p-6 text-board shadow-note" style={{ transform: 'rotate(-.6deg)' }}><span className={`rounded px-2 py-1 font-mono text-[10px] font-semibold uppercase ${gig.tag}`}>{gig.category}</span><h2 className="mt-5 font-display text-2xl font-bold">{gig.title}</h2><p className="mt-2 text-xs text-[#6b6980]">Posted 3 days ago · {gig.reviews} orders completed</p><p className="mt-5 text-sm leading-6 text-[#4d4b5c]">{gig.description}</p><p className="mt-6 font-mono text-2xl font-medium">{gig.price}</p></div><div className="space-y-4"><div className="rounded-xl border border-white/10 bg-board p-5"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-lav font-mono text-xs font-bold text-board">{gig.person.split(' ').map((name) => name[0]).join('')}</div><div><p className="text-sm font-semibold">{gig.person}</p><p className="mt-1 font-mono text-[11px] text-white/45">{gig.rating} · {gig.reviews} gigs completed</p></div></div><button className="mt-5 w-full rounded-lg border border-white/20 px-4 py-2 text-xs font-semibold hover:border-white/50">View profile</button></div><div className="rounded-xl border border-white/10 bg-board p-5"><p className="mb-3 text-xs text-white/50">Ready to request this gig?</p><button className="w-full rounded-lg bg-coral px-4 py-3 text-sm font-semibold text-board hover:bg-[#e1493a]">Request this gig · {gig.price}</button></div></div></div></div></div> }

export default App
